apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myportfolio
  namespace: default
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`whoami.learningreliability.site`)
      kind: Rule
      services:
        - name: myportfolio
          port: 80
    - match: Host(`kaunhumai.learningreliability.site`)
      kind: Rule
      services:
        - name: myportfolio
          port: 80
  tls:
    secretName: linode-dns01-learningreliability-tls